### ISSUE TITLE
Update libdeflate please?

### ISSUE THREAD

**Issue by ap** [benkasminbullock/gzip-libdeflate#1]
Recent versions have substantive performance bumps.

**Comment by benkasminbullock** [comment]
Trial version using 1.14 version of library is on CPAN now. Once testing is finished I will update it to 0.04.

https://metacpan.org/release/BKB/Gzip-Libdeflate-0.03_01

**Comment by benkasminbullock** [comment]
I am sorry about the delay in releasing this but the CPAN testers web site seems to be completely unresponsive at the moment.

http://matrix.cpantesters.org/?dist=Gzip-Libdeflate+0.03_01

http://fast-matrix.cpantesters.org/?dist=Gzip-Libdeflate%200.03_01

I haven't released any Perl XS modules for some time so I haven't been checking why it is that these sites are not being updated. It might be temporary, or the sites might be failing.

It's quite unwise to release an XS module without looking at the test results for a trial version so I want to put off the next release until some kind of response is made.

**Comment by ap** [comment]
Yeah, of course. I’m not in that kind of hurry.

Last release that had any reports processed as far as I can tell is
https://metacpan.org/release/MLAWREN/OptArgs2-2.0.0
from Wednesday last week (and that’s not a lot of reports for a week). Everything on https://metacpan.org/recent since that release has a blank spot for CPAN Testers stats – yours included. Unsurprisingly, http://cpantesters.org/ says “Status: OVERLOADED”. What is actually odd however is that the most recent report listed on http://cpantesters.org/recent.html is from 2012. Clearly there is some kind of an ops glitch going on.

**Comment by benkasminbullock** [comment]
It may be that the CPAN testers website has been abandoned.

cpantesters.org

 I understood that Doug Bell (preaction) took over the administration of the web site, but it doesn't seem to be updated. Links such as "blog" and "wiki" on that website go nowhere, they are redirected to a dead domain called "grango.org".

http://cpanblog.grango.org/
http://cpanwiki.grango.org/

The bottom of the page still claims that Barbie is in charge of it and that it is using the Labyrinth web framework.

The performance graph has nosedived:

http://stats.cpantesters.org/perform.html#build1

I looked at the mailing list for CPAN testers and there are just a few emails this year from James Keenan noting that the web site has been out of action since 5 October.

https://groups.google.com/g/perl.cpan.testers.discuss?pli=1

I also looked at Preaction's twitter for clues.

https://twitter.com/preaction

But there is nothing.

🤷

I may have to test on Windows and Linux as well as on FreeBSD with recent versions of Perl and then release the module without cpan testers results.

**Comment by benkasminbullock** [comment]
I've tested the new release on FreeBSD and Windows operating system, not much else I can do at the moment, so I've released this upgrade as version 0.04 to CPAN. This issue is now closed.

**Comment by ap** [comment]
> Links such as "blog" and "wiki" on that website go nowhere, they are redirected to a dead domain called "grango.org".
> 
> http://cpanblog.grango.org/
> http://cpanwiki.grango.org/

Those always ran separately from the CPAN Testers site itself, even when they were subdomains under the cpantesters.org umbrella. Grango.org was some kind of personal domain of Barbie’s.

> The bottom of the page still claims that Barbie is in charge of it and that it is using the Labyrinth web framework.

Barbie is out but the Labyrinth framework part is still correct AFAIK.

So yeah, this all points to incomplete hand-over. But the site itself did go on to work in this state for years hence, so that in itself doesn’t mean much.

> I looked at the mailing list for CPAN testers and there are just a few emails this year from James Keenan noting that the web site has been out of action since 5 October.
> 
> https://groups.google.com/g/perl.cpan.testers.discuss?pli=1

I see lots more traffic in 2022 than just that thread. Even if there wasn’t, though, it’s not that unusual for some piece of Perl ecosystem infrastructure to hum along with a largely silent mailing list; while there are still people keeping the lights on, hardly nobody is *excited* to build, or build up, Perl stuff anymore. However, this is a general list, not about the CPAN Testers site itself but for all of the people running CPAN tester rigs etc, so the extra list traffic doesn’t say much about the maintenance state of the site. More illuminating is to do a search for “Doug Bell”: not much comes up, and that which does is all about the difficulties of keeping the lights on.

[I pointed out the decline in the number of testers](http://blogs.perl.org/users/aristotle/2021/07/cpantesters-decline.html) some time ago and I remember Doug responding with bitterness somewhere (Twitter?) – which was misplaced, of course, but which I also entirely understand.

I’m going to assume the broken report processing will be sorted out sooner or later. If Doug isn’t able to anymore, probably someone else will step up and take over operations. But Doug probably can’t tend to it quickly (since else he already would have, probably), and someone else taking over and making things go again isn’t going to happen overnight – so either way it will take some time.

**Comment by ap** [comment]
> I've released this upgrade as version 0.04 to CPAN. This issue is now closed.

Thank you!

You forgot to update the POD btw: 🙂 https://github.com/benkasminbullock/gzip-libdeflate/blob/13319557abdc44b51c289c175428fc89b025cdf5/libdeflate-one.c#L662 But: https://github.com/benkasminbullock/gzip-libdeflate/blob/13319557abdc44b51c289c175428fc89b025cdf5/make-pod.pl#L36

**Comment by ap** [comment]
Btw,
http://api.cpantesters.org/v3/summary/Gzip-Libdeflate/0.03_01
http://api.cpantesters.org/v3/summary/Gzip-Libdeflate/0.04

**Comment by ap** [comment]
It’s working again now.
